import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteButton, RelatedButtonModel, CompleteUser, RelatedUserModel } from "./index"

export const PhoneNumerModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  locale: z.nativeEnum(Locale),
  isPublished: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
  /**
   * phone value
   */
  value: z.string().trim().min(1).max(120),
  /**
   * phone label
   */
  label: z.string().trim().min(1).max(120).optional().nullish(),
})

export interface CompletePhoneNumer extends z.infer<typeof PhoneNumerModel> {
  buttons: CompleteButton[]
  user?: CompleteUser | null
}

/**
 * RelatedPhoneNumerModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedPhoneNumerModel: z.ZodSchema<CompletePhoneNumer> = z.lazy(() => PhoneNumerModel.extend({
  /**
   * buttons with this phone number
   */
  buttons: RelatedButtonModel.array(),
  user: RelatedUserModel.nullish(),
}))
