import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteButton, RelatedButtonModel } from "./index"

export const EmailModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
  /**
   * email value
   */
  value: z.string().trim().min(1).max(320),
  /**
   * email label
   */
  label: z.string().trim().min(1).max(320).optional().nullish(),
})

export interface CompleteEmail extends z.infer<typeof EmailModel> {
  buttons: CompleteButton[]
}

/**
 * RelatedEmailModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedEmailModel: z.ZodSchema<CompleteEmail> = z.lazy(() => EmailModel.extend({
  /**
   * buttons with this email
   */
  buttons: RelatedButtonModel.array(),
}))
