import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteButton, RelatedButtonModel, CompletePage, RelatedPageModel } from "./index"

export const HeaderModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
})

export interface CompleteHeader extends z.infer<typeof HeaderModel> {
  buttons: CompleteButton[]
  pages: CompletePage[]
}

/**
 * RelatedHeaderModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedHeaderModel: z.ZodSchema<CompleteHeader> = z.lazy(() => HeaderModel.extend({
  /**
   * header buttons
   */
  buttons: RelatedButtonModel.array(),
  /**
   * pages with this header
   */
  pages: RelatedPageModel.array(),
}))
