import * as z from "zod"
import { Locale } from "@prisma/client"

export const LeadModel = z.object({
  /**
   * The unique identifier for the lead
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * user url from which the request came
   */
  url: z.string().trim().min(1).max(10000),
  /**
   * form name on the page from which the lead came
   */
  formName: z.string().trim().min(1).max(100),
  /**
   * user ip
   */
  ip: z.string().trim().min(1).max(39),
  /**
   * Google analitics client ID
   */
  gmClientId: z.string().trim().min(1).max(100).optional().nullish(),
  /**
   * Yandex metrics ID
   */
  ymClientID: z.string().trim().min(1).max(100).optional().nullish(),
  /**
   * user agent
   */
  userAgent: z.string().trim().min(1).max(100),
  /**
   * user utm_source url param
   */
  utm_source: z.string().trim().min(1).max(400).optional().nullish(),
  /**
   * user utm_medium url param
   */
  utm_medium: z.string().trim().min(1).max(400).optional().nullish(),
  /**
   * user utm_campaign url param
   */
  utm_campaign: z.string().trim().min(1).max(400).optional().nullish(),
  /**
   * user utm_content url param
   */
  utm_content: z.string().trim().min(1).max(400).optional().nullish(),
  /**
   * user utm_term url param
   */
  utm_term: z.string().trim().min(1).max(400).optional().nullish(),
  /**
   * createdAt user date at the request time
   */
  createdAt: z.coerce.date(),
  /**
   * lead locale
   */
  locale: z.nativeEnum(Locale),
})
