import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteParameterValue, RelatedParameterValueModel, CompleteProduct, RelatedProductModel } from "./index"

export const ParameterModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
  /**
   * parameter title
   */
  title: z.string().trim().min(1).max(240),
  /**
   * whether parameter is highlighted
   */
  isHighlighted: z.boolean(),
})

export interface CompleteParameter extends z.infer<typeof ParameterModel> {
  values: CompleteParameterValue[]
  products: CompleteProduct[]
}

/**
 * RelatedParameterModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedParameterModel: z.ZodSchema<CompleteParameter> = z.lazy(() => ParameterModel.extend({
  /**
   * parameter values
   */
  values: RelatedParameterValueModel.array(),
  /**
   * parameter product
   */
  products: RelatedProductModel.array(),
}))
