import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteParameter, RelatedParameterModel } from "./index"

export const ParameterValueModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
  /**
   * ParameterValue value
   */
  value: z.string().trim().min(1).max(240),
  parameterId: z.string(),
})

export interface CompleteParameterValue extends z.infer<typeof ParameterValueModel> {
  parameter: CompleteParameter
}

/**
 * RelatedParameterValueModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedParameterValueModel: z.ZodSchema<CompleteParameterValue> = z.lazy(() => ParameterValueModel.extend({
  /**
   * ParameterValue parameter
   */
  parameter: RelatedParameterModel,
}))
