import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteProduct, RelatedProductModel } from "./index"

export const ProductTestimonialModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
  /**
   * ProductTestimonial title
   */
  title: z.string().trim().min(3).max(80),
})

export interface CompleteProductTestimonial extends z.infer<typeof ProductTestimonialModel> {
  product: CompleteProduct[]
}

/**
 * RelatedProductTestimonialModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedProductTestimonialModel: z.ZodSchema<CompleteProductTestimonial> = z.lazy(() => ProductTestimonialModel.extend({
  /**
   * ProductTestimonial product
   */
  product: RelatedProductModel.array(),
}))
