import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteCategory, RelatedCategoryModel, CompleteForm, RelatedFormModel, CompleteImage, RelatedImageModel, CompleteSectionProduct, RelatedSectionProductModel, CompleteParameter, RelatedParameterModel, CompleteProductTestimonial, RelatedProductTestimonialModel, CompleteButton, RelatedButtonModel } from "./index"

export const ProductModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
  /**
   * product slug
   */
  slug: z.string().trim(),
  /**
   * product name
   */
  name: z.string().trim().min(2).max(100),
  /**
   * short descriptoon
   */
  description: z.string().trim().min(3).max(120),
  /**
   * product description
   */
  longDescription: z.string().trim().min(3).max(1200).optional().nullish(),
  categorySlug: z.string(),
  formId: z.string(),
  imageId: z.string(),
})

export interface CompleteProduct extends z.infer<typeof ProductModel> {
  category: CompleteCategory
  form: CompleteForm
  image: CompleteImage
  sectionProduct: CompleteSectionProduct[]
  parameters: CompleteParameter[]
  productTestimonials: CompleteProductTestimonial[]
  buttons: CompleteButton[]
}

/**
 * RelatedProductModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedProductModel: z.ZodSchema<CompleteProduct> = z.lazy(() => ProductModel.extend({
  /**
   * product category
   */
  category: RelatedCategoryModel,
  /**
   * product form
   */
  form: RelatedFormModel,
  /**
   * product image
   */
  image: RelatedImageModel,
  /**
   * product sectionProducts
   */
  sectionProduct: RelatedSectionProductModel.array(),
  /**
   * product parameters
   */
  parameters: RelatedParameterModel.array(),
  /**
   * product testimonials
   */
  productTestimonials: RelatedProductTestimonialModel.array(),
  /**
   * product buttons
   */
  buttons: RelatedButtonModel.array(),
}))
