import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteTestimonial, RelatedTestimonialModel, CompletePage, RelatedPageModel } from "./index"

export const SectionTestimonialsModel = z.object({
  /**
   * The unique identifier for the lead
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * section locale
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether SectionTestimonials is published
   */
  isPublished: z.boolean(),
  /**
   * section index
   */
  index: z.number().int(),
  /**
   * section title
   */
  title: z.string().trim().min(1).max(60),
})

export interface CompleteSectionTestimonials extends z.infer<typeof SectionTestimonialsModel> {
  testimonials: CompleteTestimonial[]
  pages: CompletePage[]
}

/**
 * RelatedSectionTestimonialsModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedSectionTestimonialsModel: z.ZodSchema<CompleteSectionTestimonials> = z.lazy(() => SectionTestimonialsModel.extend({
  /**
   * section testimonials
   */
  testimonials: RelatedTestimonialModel.array(),
  /**
   * pages with this section
   */
  pages: RelatedPageModel.array(),
}))
