import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteCategory, RelatedCategoryModel, CompletePage, RelatedPageModel } from "./index"

export const SectionCatalogModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * locale of the record
   * @default {ru}
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether record is published
   * @default {false}
   */
  isPublished: z.boolean(),
  /**
   * date of record creation
   * @default {now()}
   */
  createdAt: z.date(),
  /**
   * date of record update
   * @default {now()}
   */
  updatedAt: z.date(),
  /**
   * section title
   */
  title: z.string().trim().min(1).max(60),
})

export interface CompleteSectionCatalog extends z.infer<typeof SectionCatalogModel> {
  categories: CompleteCategory[]
  pages: CompletePage[]
}

/**
 * RelatedSectionCatalogModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedSectionCatalogModel: z.ZodSchema<CompleteSectionCatalog> = z.lazy(() => SectionCatalogModel.extend({
  /**
   * section categories
   */
  categories: RelatedCategoryModel.array(),
  /**
   * pages with this section
   */
  pages: RelatedPageModel.array(),
}))
