import * as z from "zod"
import { Locale } from "@prisma/client"
import { CompleteButton, RelatedButtonModel, CompleteImage, RelatedImageModel, CompleteSectionGallery, RelatedSectionGalleryModel } from "./index"

export const SlideModel = z.object({
  /**
   * The unique identifier for the lead
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * slide locale
   */
  locale: z.nativeEnum(Locale),
  /**
   * whether Slide is published
   */
  isPublished: z.boolean(),
  /**
   * slide title
   */
  title: z.string().trim().min(3).max(3000),
  /**
   * slide subtitle
   */
  subtitle: z.string().trim().min(3).max(3000).optional().nullish(),
  /**
   * Whether the slide has cornered rectangle positioned just right of the image
   */
  isDecoration: z.boolean(),
  imageId: z.string(),
  sectionGalleryId: z.string().nullish(),
})

export interface CompleteSlide extends z.infer<typeof SlideModel> {
  buttons: CompleteButton[]
  image: CompleteImage
  sectionGallery?: CompleteSectionGallery | null
}

/**
 * RelatedSlideModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedSlideModel: z.ZodSchema<CompleteSlide> = z.lazy(() => SlideModel.extend({
  /**
   * Slide button
   */
  buttons: RelatedButtonModel.array(),
  /**
   * Slide image
   */
  image: RelatedImageModel,
  /**
   * SectionGallery with this slide
   */
  sectionGallery: RelatedSectionGalleryModel.nullish(),
}))
