import * as z from "zod"

export const VerificationTokenModel = z.object({
  /**
   * The unique identifier for the record
   * @default {Generated by database}
   */
  id: z.string(),
  identifier: z.string(),
  token: z.string(),
  expires: z.date(),
})
